### ISSUE TITLE
Inventory Error + Character Creation Error

### ISSUE THREAD

**Issue by ItzBradleey** [CloudSixteen/Clockwork#191] opened 2015-03-09 21:15 UTC
Once opening the inventory, the follow error occurs and spams the console

[ERROR] gamemodes/clockwork/framework/derma/cl_inventory.lua:382: attempt to perform arithmetic on local 'maximumWeight' (a nil value)
  1. unknown - gamemodes/clockwork/framework/derma/cl_inventory.lua:382

[ERROR] gamemodes/clockwork/framework/derma/cl_inventory.lua:403: attempt to concatenate a nil value
  1. unknown - gamemodes/clockwork/framework/derma/cl_inventory.lua:403

When you also create a create and choose male or female, you receive the follow error

[ERROR] lua/vgui/dform.lua:132: bad argument #1 to 'RunConsoleCommand' (string expected, got nil)
  1. RunConsoleCommand - [C]:-1
   2. OnSelect - lua/vgui/dform.lua:132
    3. ChooseOption - lua/vgui/dcombobox.lua:95
     4. DoClick - lua/vgui/dcombobox.lua:194
      5. OnMouseReleased - lua/vgui/dlabel.lua:204
       6. unknown - lua/vgui/dmenuoption.lua:116

**Comment by Gr4Ss** [comment] 2015-03-09 21:24
Looking into it

**Comment by ItzBradleey** [comment] 2015-03-09 21:25
I also have a screenshot of the console for you, if it is at any use...

http://i.imgur.com/TUxy1Au.png

**Comment by Gr4Ss** [comment] 2015-03-09 21:26
That icon stuff is because of checkpoint, I pushed a fix for it to the plugin center already.

**Comment by fayzgolden666** [comment] 2015-03-09 21:47
yeah, getting the max weight thing too

**Comment by ItzBradleey** [comment] 2015-03-09 21:48
There are also multiple errors with giving flags to players.

**Comment by VortixDev** [comment] 2015-06-14 22:15
The first error has been fixed, the rest cannot be reproduced. Thank you for reporting this.

**Closed by VortixDev** 2015-06-14 22:15 UTC
